name: Pipeline Production Sax

on:
  workflow_dispatch:

jobs:
  Release-Tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do c√≥digo
      uses: actions/checkout@v3

    - name: Configurar Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        
    - name: Criar Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          üöÄ Mudan√ßas nesta vers√£o:
          - Adicione as notas da release aqui.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        
    - name: Criar Tag
      id: create_tag
      run: echo "tag=v${{ github.run_number }}" >> $GITHUB_ENV

    - name: Checkout do c√≥digo com a nova tag
      uses: actions/checkout@v3
      with:
        ref: ${{ env.tag }}

  Build:
    runs-on: ubuntu-latest
    needs: Release-Tag

    steps:
    - name: Checkout do c√≥digo
      uses: actions/checkout@v3

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Verificar arquivos do projeto
      run: ls -la

    - name: Copiar .env
      run: |
        if [ -f .env.example ]; then
          cp .env.example .env
        else
          echo "‚ö†Ô∏è Arquivo .env.example n√£o encontrado!"
          exit 1
        fi

    - name: Atualizar depend√™ncias com Composer
      run: |
        if [ ! -f composer.json ]; then
          echo "‚ùå Arquivo composer.json n√£o encontrado!"
          exit 1
        fi
        composer update --no-ansi --no-interaction --no-progress

    - name: Instalar depend√™ncias do projeto
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Gerar chave do Laravel
      run: php artisan key:generate

    - name: Configurar permiss√µes
      run: chmod -R 775 storage bootstrap/cache

  run_pull:
    needs: Build
    name: Deploy para Servidor
    runs-on: ubuntu-latest

    steps:
    - name: Configurar SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Teste de conex√£o SSH (Debug)
      run: ssh -v -i ~/.ssh/id_ed25519 -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

    - name: Executar Deploy no Servidor
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.WORK_DIR }} 
          ./pipeline-sax-producion.sh '${{ github.ref_name }}'
