name: Pipeline Production Sax

on:
  workflow_dispatch:

jobs:
  Release-Tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Changes in this release:
          - Add your release notes here
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}  # Use o PAT em vez do GITHUB_TOKEN

    - name: Create Tag
      id: create_tag
      run: echo "tag=v${{ github.run_number }}" >> $GITHUB_ENV

  Build:
    runs-on: ubuntu-latest
    needs: Release-Tag

    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      with:
        ref: ${{ env.tag }}

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Copiar .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Instalar dependências
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Gerar chave artisan
      run: php artisan key:generate

    - name: Ajustar permissões
      run: chmod -R 775 storage bootstrap/cache

  run_pull:
    needs: Build
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Conectar ao Servidor e Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.WORK_DIR }}
          cd /var/www/html/dv-collection && git fetch && git pull
          cd /var/www/html/majesticresidence && git fetch && git pull
          cd /var/www/html/sax && git fetch && git pull
          cd /var/www/html/saxnoivas && git fetch && git pull
          cd /var/www/html/saxstage && git fetch && git pull
