name: Pipeline Production Sax

on:
  workflow_dispatch:

jobs:
  Release-Tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Changes in this release:
          - Add your release notes here
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        
    - name: Create Tag
      id: create_tag
      run: echo ::set-output name=tag::v${{ github.run_number }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.create_tag.outputs.tag }}

  Build:
    runs-on: ubuntu-latest
    needs: Release-Tag

    steps:
    - uses: actions/checkout@v3
      with:
        php-version: '8.1'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Instalar dependẽncias e pacotes
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Gerar chave artisan
      run: php artisan key:generate

    - name: Permissões do diretório
      run: chmod -R 775 storage bootstrap/cache

  run_pull:
    needs: Build
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Executando Conexão SSH com o Servidor
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: cd ${{ secrets.WORK_DIR }} && ./pipeline-sax-producion.sh '${{ github.ref_name }}'
    - name: Desconectando do servidor
      run: exit
