name: Deploy Laravel Projects

on:
  push:
    branches:
      - main
      - production  # Ajuste conforme sua branch principal
  pull_request:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [sax, dv-collection, saxstage, saxnoivas]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Verificar estrutura do projeto
        run: |
          pwd
          ls -la
          cd ${{ matrix.project }} && ls -la

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
        env:
          COMPOSER_PROCESS_TIMEOUT: 0

      - name: Criar arquivo .env caso não exista
        working-directory: ${{ matrix.project }}
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Instalar dependências PHP
        working-directory: ${{ matrix.project }}
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Gerar chave da aplicação
        working-directory: ${{ matrix.project }}
        run: php artisan key:generate

      - name: Executar migrações e seeders
        working-directory: ${{ matrix.project }}
        run: php artisan migrate --force && php artisan db:seed --force

      - name: Limpar cache e otimizar
        working-directory: ${{ matrix.project }}
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          php artisan config:cache
          php artisan route:cache

      - name: Compilar assets
        working-directory: ${{ matrix.project }}
        run: npm install && npm run prod

      - name: Reiniciar o servidor (caso necessário)
        run: sudo systemctl restart nginx php8.1-fpm
