name: Pipeline Production

on:
   workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        php-version: '8.1'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Instalar dependẽncias e pacotes
      run: composer install --no-interaction --no-plugins --no-scripts


    - name: Gerar chave artisan
      run: php artisan key:generate

    - name: Permissões do diretório
      run: chmod -R 775 storage bootstrap/cache

  run_pull:
    needs: Build
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Executando Conexão SSH com o Servidor
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST_LARAVEL9 }}
        username: ${{ secrets.SSH_USER2 }}
        key: ${{ secrets.SSH_PRIVATE_KEY_L9 }}
        port: ${{ secrets.PORT }}
        script: cd ${{ secrets.WORK_DIR }} && ./pipeline-laravel9-production.sh '${{ github.ref_name }}'
    - name: Desconectando do servidor
      run: exit
