name: Pipeline Production Sax

on:
  push:
    tags:
      - 'v*'  # Executa quando há push em uma tag (versão)
  workflow_dispatch:  # Permite executar manualmente a pipeline

jobs:
  Update-Code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Garante que o histórico completo seja obtido, importante para tags e releases

    - name: Set git config user.name
      run: |
        git config user.name "eduardoDahmer1"
        git config user.email "your-email@example.com"  # Substitua pelo seu e-mail

    - name: Set git config for safe directory
      run: |
        git config --global --add safe.directory /home/runner/work/sax-fullservice/sax-fullservice

    - name: Fetch latest code
      run: git fetch --all

    - name: Pull latest changes from remote
      run: git pull origin ${{ github.ref }}  # Faz pull da branch/tag atual

  Create-Release:
    runs-on: ubuntu-latest
    needs: Update-Code

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Garante que o histórico completo seja obtido, importante para tags e releases

    - name: Create GitHub release
      uses: actions/create-release@v1
      with:
        tag_name: v109
        release_name: Release 109
        body: |
          Changes in this release:
          - Add your release notes here
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Passando o token de autenticação gerado pelo GitHub

  run_pull:
    needs: Update-Code
    name: Pull latest code and deploy to server
    runs-on: ubuntu-latest

    steps:
    - name: SSH into the server and pull latest changes
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/dv-collection && git fetch && git pull
          cd /var/www/html/majesticresidence && git fetch && git pull
          cd /var/www/html/sax && git fetch && git pull
          cd /var/www/html/saxnoivas && git fetch && git pull
          cd /var/www/html/saxstage && git fetch && git pull
